#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3.4'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  network-automation:
    ports:
      - 22:22
    volumes:
      - .:/ansible
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes: 
  app: 
